### ISSUE TITLE
Refactor CI into a single linked workflow

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#374]
- Change to run checks only or pull request to reduce the number
- Remove run on pull in preference for run on pull request, something like:
```yaml
on:
  push:
  branches:
    - master
  tags:
    - '*'
  pull_request:
```

e.g. https://github.com/DiamondLightSource/fastcs-odin/actions/runs/22867440260
